pose_estimation:
    ros__parameters:
        pattern: "CHESSBOARD"
        image_topic: "/camera_1/rgb/image_raw"
        camera_info_topic: "/camera_1/rgb/camera_info"
        publish_image_topic: "/bartek/image/detected"
        marker_frame_name: "calib_board"
        camera_frame: "camera_1/camera_base"
        width: 9
        height: 6
        dictionary: "DICT_4X4_50"
        chessboard_square_size: 0.04
        circle_grid_seperation: 0.035
        aruco_board_marker_size: 0.0256
        aruco_board_marker_seperation: 0.0066
        charuco_board_marker_size: 0.022
        charuco_board_square_size: 0.03