/simple_controller:
  ros__parameters:

    error_margin: 0.005

    #friction

    # Fv_gain_0: 0.
    # FFa_gain_0: 0.
    # Kd_gain_0: 0.1
    # Ki_gain_0: 10.
    # Kp_gain_0: 80.0
    # Coulomb_friction_0: 0.
    # i_clamp_h_0: 10.
    # i_clamp_l_0: -10.


    FFv_gain_0: 0.0
    FFa_gain_0: 0.
    Kd_gain_0: 0.0
    Ki_gain_0: 100.0
    Kp_gain_0: 200.0
    Coulomb_friction_0: 0.
    i_clamp_h_0: 40.
    i_clamp_l_0: -40.

    FFv_gain_1: 0.
    FFa_gain_1: 0.
    Kd_gain_1: 0.0
    Ki_gain_1: 100.0
    Kp_gain_1: 200.0
    Coulomb_friction_1: 0.0
    i_clamp_h_2: 40.
    i_clamp_l_2: -40.

    FFv_gain_2: 0.
    FFa_gain_2: 0.
    Kd_gain_2: 0.0
    Ki_gain_2: 100.0
    Kp_gain_2: 200.0
    Coulomb_friction_2: 0.
    i_clamp_h_2: 40.
    i_clamp_l_2: -40.


    use_sim_time: false

    # FFv_gain_0: 12.0
    # Kd_gain_0: 20.0
    # Ki_gain_0: 1.0
    # Kp_gain_0: 30.0
    # Coulomb_friction_0: 12.5