/simple_controller:
  ros__parameters:
    error_margin: 0.005

    #friction

    Fv_gain_0: 0.
    FFa_gain_0: 0.
    Kd_gain_0: 0.1
    Ki_gain_0: 5.
    Kp_gain_0: 20.0
    Coulomb_friction_0: 0.
    i_clamp_h_0: 10.
    i_clamp_l_0: -10.


    # FFv_gain_0: 0.0
    # FFa_gain_0: 0.
    # Kd_gain_0: 20.0
    # Ki_gain_0: 40.0
    # Kp_gain_0: 150.0
    # Coulomb_friction_0: 0.
    # i_clamp_h_0: 0.4
    # i_clamp_l_0: -0.4

    FFv_gain_0: 0.
    FFa_gain_0: 0.
    Kd_gain_0: 0.1
    Ki_gain_0: 5.
    Kp_gain_0: 20.0
    Coulomb_friction_0: 0.
    i_clamp_h_0: 10.
    i_clamp_l_0: -10.

    # FFv_gain_1: 1.5
    # FFa_gain_1: 8.
    # Kd_gain_1: 30.0
    # Ki_gain_1: 5.0
    # Kp_gain_1: 165.0
    # Coulomb_friction_1: 6.5

    FFv_gain_1: 0.
    FFa_gain_1: 0.
    Kd_gain_1: 1.0
    Ki_gain_1: 15.0
    Kp_gain_1: 15.0
    Coulomb_friction_1: 0.

    FFv_gain_2: 0.
    FFa_gain_2: 0.
    Kd_gain_2: 1.0
    Ki_gain_2: 15.0
    Kp_gain_2: 15.0
    Coulomb_friction_2: 0.

    use_sim_time: false

    # FFv_gain_0: 12.0
    # Kd_gain_0: 20.0
    # Ki_gain_0: 1.0
    # Kp_gain_0: 30.0
    # Coulomb_friction_0: 12.5