/simple_controller:
  ros__parameters:
    error_margin: 0.005

    #friction

    Fv_gain_0: 0.
    FFa_gain_0: 0.
    Kd_gain_0: 0.1
    Ki_gain_0: 5.
    Kp_gain_0: 20.0
    Coulomb_friction_0: 0.
    i_clamp_h_0: 10.
    i_clamp_l_0: -10.

    Fv_gain_1: 0.
    FFa_gain_1: 0.
    Kd_gain_1: 0.1
    Ki_gain_1: 5.
    Kp_gain_1: 20.0
    Coulomb_friction_1: 0.
    i_clamp_h_1: 10.
    i_clamp_l_1: -10.


    Fv_gain_2: 0.
    FFa_gain_2: 0.
    Kd_gain_2: 0.1
    Ki_gain_2: 5.
    Kp_gain_2: 20.0
    Coulomb_friction_2: 0.
    i_clamp_h_2: 10.
    i_clamp_l_2: -10.


    Fv_gain_3: 0.
    FFa_gain_3: 0.
    Kd_gain_3: 0.1
    Ki_gain_3: 5.
    Kp_gain_3: 20.0
    Coulomb_friction_3: 0.
    i_clamp_h_3: 10.
    i_clamp_l_3: -10.
    
    Fv_gain_4: 0.
    FFa_gain_4: 0.
    Kd_gain_4: 0.1
    Ki_gain_4: 5.
    Kp_gain_4: 20.0
    Coulomb_friction_4: 0.
    i_clamp_h_4: 10.
    i_clamp_l_4: -10.

    Fv_gain_5: 0.
    FFa_gain_5: 0.
    Kd_gain_5: 0.1
    Ki_gain_5: 5.
    Kp_gain_5: 20.0
    Coulomb_friction_5: 0.
    i_clamp_h_5: 10.
    i_clamp_l_5: -10.



