parameters=[
    {'cam1_depth_enabled': True},
    {'cam1_depth_mode':"WFOV_2X2BINNED"},
    {'cam1_color_enabled':True},
    {'cam1_color_format':"bgra"},
    {'cam1_color_resolution':"720P"},
    {'cam1_fps': 5},
    {'cam1_point_cloud':True},
    {'cam1_rgb_point_cloud':False},
    {'cam1_point_cloud_in_depth_frame':True},
    {'cam1_sensor_sn':""},
    {'cam1_recording_file':""},
    {'cam1_recording_loop_enabled':False},
    {'cam1_body_tracking_enabled':False},
    {'cam1_body_tracking_smoothing_factor':1.0},
    {'cam1_rescale_ir_to_mono8':False},
    {'cam1_ir_mono8_scaling_factor':1.0},
    {'cam1_imu_rate_target':0},
    {'cam1_wired_sync_mode':1},
    {'cam1_subordinate_delay_off_master_usec':0},

    {'cam2_depth_enabled':True},
    {'cam2_depth_mode':"WFOV_2X2BINNED"},
    {'cam2_color_enabled':True},
    {'cam2_color_format':"bgra"},
    {'cam2_color_resolution':"720P"},
    {'cam2_fps':5},
    {'cam2_point_cloud':True},
    {'cam2_rgb_point_cloud':False},
    {'cam2_point_cloud_in_depth_frame':True},
    {'cam2_sensor_sn':""},
    {'cam2_recording_file':""},
    {'cam2_recording_loop_enabled':False},
    {'cam2_body_tracking_enabled':False},
    {'cam2_body_tracking_smoothing_factor':1.0},
    {'cam2_rescale_ir_to_mono8':False},
    {'cam2_ir_mono8_scaling_factor':1.0},
    {'cam2_imu_rate_target':0},
    {'cam2_wired_sync_mode':2},
    {'cam2_subordinate_delay_off_master_usec': 200},

    {'depth_change_factor': 0.01},
    {'smoothing_size': 4.0},
    {'shadow_treshold': 0.5},
    {'rect_size': 5}
]