table_area:
  min:
    x: 0
    y: -1.2
    z: 0
  max:
    x: 1.2
    y: 1.2
    z: 1
tools_area: 
  min: 
    x: 0.1
    y: -0.85
    z: 0.0
  max: 
    x: 0.7
    y: -0.55
    z: 1.0
item_area: 
  min: 
    x: 0.1
    y: 0.55
    z: 0.0
  max: 
    x: 0.7
    y: 1.1
    z: 1.0
operating_area: 
  min: 
    x: 0.1
    y: -0.55
    z: 0.0
  max: 
    x: 0.7
    y: 0.55
    z: 1.0
