# p_0_0:
#   x: 70.0
#   y: 110.0
#   z: 0.0
# p_0_1:
#   x: 70.0
#   y: 90.0
#   z: 0.0
# p_0_2:
#   x: 70.0
#   y: 70.0
#   z: 0.0
# p_0_3:
#   x: 70.0
#   y: 50.0
#   z: 0.0
# p_0_4:
#   x: 70.0
#   y: 30.0
#   z: 0.0
# p_0_5:
#   x: 70.0
#   y: 10.0
#   z: 0.0
# p_0_6:
#   x: 70.0
#   y: -10.0
#   z: 0.0
# p_0_7:
#   x: 70.0
#   y: -30.0
#   z: 0.0
# p_0_8:
#   x: 70.0
#   y: -50.0
#   z: 0.0
# p_0_9:
#   x: 70.0
#   y: -70.0
#   z: 0.0
# p_0_10:
#   x: 70.0
#   y: -90.0
#   z: 0.0 
# p_0_11:
#   x: 70.0
#   y: -110.0
#   z: 0.0 
# p_1_0:
#   x: 60.0
#   y: 110.0
#   z: 0.0
# p_1_1:
#   x: 60.0
#   y: 90.0
#   z: 0.0
# p_1_2:
#   x: 60.0
#   y: 70.0
#   z: 0.0
# p_1_3:
#   x: 60.0
#   y: 50.0
#   z: 0.0
# p_1_4:
#   x: 60.0
#   y: 30.0
#   z: 0.0
# p_1_5:
#   x: 60.0
#   y: 10.0
#   z: 0.0
# p_1_6:
#   x: 60.0
#   y: -10.0
#   z: 0.0
# p_1_7:
#   x: 60.0
#   y: -30.0
#   z: 0.0
# p_1_8:
#   x: 60.0
#   y: -50.0
#   z: 0.0
# p_1_9:
#   x: 60.0
#   y: -70.0
#   z: 0.0
# p_1_10:
#   x: 60.0
#   y: -90.0
#   z: 0.0 
# p_1_11:
#   x: 60.0
#   y: -110.0
#   z: 0.0 
# p_2_0:
#   x: 50.0
#   y: 110.0
#   z: 0.0
# p_2_1:
#   x: 50.0
#   y: 90.0
#   z: 0.0
# p_2_2:
#   x: 50.0
#   y: 70.0
#   z: 0.0
# p_2_3:
#   x: 50.0
#   y: 50.0
#   z: 0.0
# p_2_4:
#   x: 50.0
#   y: 30.0
#   z: 0.0
# p_2_5:
#   x: 50.0
#   y: 10.0
#   z: 0.0
# p_2_6:
#   x: 50.0
#   y: -10.0
#   z: 0.0
# p_2_7:
#   x: 50.0
#   y: -30.0
#   z: 0.0
# p_2_8:
#   x: 50.0
#   y: -50.0
#   z: 0.0
# p_2_9:
#   x: 50.0
#   y: -70.0
#   z: 0.0
# p_2_10:
#   x: 50.0
#   y: -90.0
#   z: 0.0 
# p_2_11:
#   x: 50.0
#   y: -110.0
#   z: 0.0 
# p_3_0:
#   x: 40.0
#   y: 110.0
#   z: 0.0
# p_3_1:
#   x: 40.0
#   y: 90.0
#   z: 0.0
# p_3_2:
#   x: 40.0
#   y: 70.0
#   z: 0.0
# p_3_3:
#   x: 40.0
#   y: 50.0
#   z: 0.0
# p_3_4:
#   x: 40.0
#   y: 30.0
#   z: 0.0
# p_3_5:
#   x: 40.0
#   y: 10.0
#   z: 0.0
# p_3_6:
#   x: 40.0
#   y: -10.0
#   z: 0.0
# p_3_7:
#   x: 40.0
#   y: -30.0
#   z: 0.0
# p_3_8:
#   x: 40.0
#   y: -50.0
#   z: 0.0
# p_3_9:
#   x: 40.0
#   y: -70.0
#   z: 0.0
# p_3_10:
#   x: 40.0
#   y: -90.0
#   z: 0.0 
# p_3_11:
#   x: 40.0
#   y: -110.0
#   z: 0.0 
# p_4_0:
#   x: 30.0
#   y: 110.0
#   z: 0.0
# p_4_1:
#   x: 30.0
#   y: 90.0
#   z: 0.0
# p_4_2:
#   x: 30.0
#   y: 70.0
#   z: 0.0
# p_4_3:
#   x: 30.0
#   y: 50.0
#   z: 0.0
# p_4_4:
#   x: 30.0
#   y: 30.0
#   z: 0.0
# p_4_5:
#   x: 30.0
#   y: 10.0
#   z: 0.0
# p_4_6:
#   x: 30.0
#   y: -10.0
#   z: 0.0
# p_4_7:
#   x: 30.0
#   y: -30.0
#   z: 0.0
# p_4_8:
#   x: 30.0
#   y: -50.0
#   z: 0.0
# p_4_9:
#   x: 30.0
#   y: -70.0
#   z: 0.0
# p_4_10:
#   x: 30.0
#   y: -90.0
#   z: 0.0 
# p_4_11:
#   x: 30.0
#   y: -110.0
#   z: 0.0 
# p_5_0:
#   x: 20.0
#   y: 110.0
#   z: 0.0
# p_5_1:
#   x: 20.0
#   y: 90.0
#   z: 0.0
# p_5_2:
#   x: 20.0
#   y: 70.0
#   z: 0.0
# p_5_3:
#   x: 20.0
#   y: 50.0
#   z: 0.0
# p_5_4: 
#   x: 20.0
#   y: 30.0
#   z: 0.0
# p_5_5:
#   x: 20.0
#   y: 10.0
#   z: 0.0
# p_5_6:
#   x: 20.0
#   y: -10.0
#   z: 0.0
# p_5_7:
#   x: 20.0
#   y: -30.0
#   z: 0.0
# p_5_8:
#   x: 20.0
#   y: -50.0
#   z: 0.0
# p_5_9:
#   x: 20.0
#   y: -70.0
#   z: 0.0
# p_5_10:
#   x: 20.0
#   y: -90.0
#   z: 0.0 
# p_5_11:
#   x: 20.0
#   y: -110.0
#   z: 0.0 

# fixed cm to meters 
p_0_0:
  x: 0.70
  y: 1.10
  z: 0.0
p_0_1:
  x: 0.70
  y: 0.90
  z: 0.0
p_0_2:
  x: 0.70
  y: 0.70
  z: 0.0
p_0_3:
  x: 0.70
  y: 0.50
  z: 0.0
p_0_4:
  x: 0.70
  y: 0.30
  z: 0.0
p_0_5:
  x: 0.70
  y: 0.10
  z: 0.0
p_0_6:
  x: 0.70
  y: -0.10
  z: 0.0
p_0_7:
  x: 0.70
  y: -0.30
  z: 0.0
p_0_8:
  x: 0.70
  y: -0.50
  z: 0.0
p_0_9:
  x: 0.70
  y: -0.70
  z: 0.0
p_0_10:
  x: 0.70
  y: -0.90
  z: 0.0 
p_0_11:
  x: 0.70
  y: -1.10
  z: 0.0 
p_1_0:
  x: 0.60
  y: 1.10
  z: 0.0
p_1_1:
  x: 0.60
  y: 0.90
  z: 0.0
p_1_2:
  x: 0.60
  y: 0.70
  z: 0.0
p_1_3:
  x: 0.60
  y: 0.50
  z: 0.0
p_1_4:
  x: 0.60
  y: 0.30
  z: 0.0
p_1_5:
  x: 0.60
  y: 0.10
  z: 0.0
p_1_6:
  x: 0.60
  y: -0.10
  z: 0.0
p_1_7:
  x: 0.60
  y: -0.30
  z: 0.0
p_1_8:
  x: 0.60
  y: -0.50
  z: 0.0
p_1_9:
  x: 0.60
  y: -0.70
  z: 0.0
p_1_10:
  x: 0.60
  y: -0.90
  z: 0.0 
p_1_11:
  x: 0.60
  y: -1.10
  z: 0.0 
p_2_0:
  x: 0.50
  y: 1.10
  z: 0.0
p_2_1:
  x: 0.50
  y: 0.90
  z: 0.0
p_2_2:
  x: 0.50
  y: 0.70
  z: 0.0
p_2_3:
  x: 0.50
  y: 0.50
  z: 0.0
p_2_4:
  x: 0.50
  y: 0.30
  z: 0.0
p_2_5:
  x: 0.50
  y: 0.10
  z: 0.0
p_2_6:
  x: 0.50
  y: -0.10
  z: 0.0
p_2_7:
  x: 0.50
  y: -0.30
  z: 0.0
p_2_8:
  x: 0.50
  y: -0.50
  z: 0.0
p_2_9:
  x: 0.50
  y: -0.70
  z: 0.0
p_2_10:
  x: 0.50
  y: -0.90
  z: 0.0 
p_2_11:
  x: 0.50
  y: -1.10
  z: 0.0 
p_3_0:
  x: 0.40
  y: 1.10
  z: 0.0
p_3_1:
  x: 0.40
  y: 0.90
  z: 0.0
p_3_2:
  x: 0.40
  y: 0.70
  z: 0.0
p_3_3:
  x: 0.40
  y: 0.50
  z: 0.0
p_3_4:
  x: 0.40
  y: 0.30
  z: 0.0
p_3_5:
  x: 0.40
  y: 0.10
  z: 0.0
p_3_6:
  x: 0.40
  y: -0.10
  z: 0.0
p_3_7:
  x: 0.40
  y: -0.30
  z: 0.0
p_3_8:
  x: 0.40
  y: -0.50
  z: 0.0
p_3_9:
  x: 0.40
  y: -0.70
  z: 0.0
p_3_10:
  x: 0.40
  y: -0.90
  z: 0.0 
p_3_11:
  x: 0.40
  y: -1.10
  z: 0.0 
p_4_0:
  x: 0.30
  y: 1.10
  z: 0.0
p_4_1:
  x: 0.30
  y: 0.90
  z: 0.0
p_4_2:
  x: 0.30
  y: 0.70
  z: 0.0
p_4_3:
  x: 0.30
  y: 0.50
  z: 0.0
p_4_4:
  x: 0.30
  y: 0.30
  z: 0.0
p_4_5:
  x: 0.30
  y: 0.10
  z: 0.0
p_4_6:
  x: 0.30
  y: -0.10
  z: 0.0
p_4_7:
  x: 0.30
  y: -0.30
  z: 0.0
p_4_8:
  x: 0.30
  y: -0.50
  z: 0.0
p_4_9:
  x: 0.30
  y: -0.70
  z: 0.0
p_4_10:
  x: 0.30
  y: -0.90
  z: 0.0 
p_4_11:
  x: 0.30
  y: -1.10
  z: 0.0 
p_5_0:
  x: 0.20
  y: 1.10
  z: 0.0
p_5_1:
  x: 0.20
  y: 0.90
  z: 0.0
p_5_2:
  x: 0.20
  y: 0.70
  z: 0.0
p_5_3:
  x: 0.20
  y: 0.50
  z: 0.0
p_5_4: 
  x: 0.20
  y: 0.30
  z: 0.0
p_5_5:
  x: 0.20
  y: 0.10
  z: 0.0
p_5_6:
  x: 0.20
  y: -0.10
  z: 0.0
p_5_7:
  x: 0.20
  y: -0.30
  z: 0.0
p_5_8:
  x: 0.20
  y: -0.50
  z: 0.0
p_5_9:
  x: 0.20
  y: -0.70
  z: 0.0
p_5_10:
  x: 0.20
  y: -0.90
  z: 0.0 
p_5_11:
  x: 0.20
  y: -1.10
  z: 0.0 
