controller_names:
  - avena_arm_controller
  # - panda_hand_controller

avena_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - avena_joint_1
    - avena_joint_2
    - avena_joint_3
    - avena_joint_4
    - avena_joint_5
    - avena_joint_6

# panda_hand_controller:
#   action_ns: gripper_cmd
#   type: GripperCommand
#   default: true
#   joints:
#     - panda_finger_joint1
