controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    avena_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # panda_hand_controller:
    #   type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


avena_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - avena_joint_1
      - avena_joint_2
      - avena_joint_3
      - avena_joint_4
      - avena_joint_5
      - avena_joint_6

# panda_hand_controller:
#   ros__parameters:
#     joint: panda_finger_joint1
