# Request
GraspData grasp_pose
float32 constrain_value
uint16 ik_trials_number
uint16 max_final_states
uint16 ompl_compare_trials
uint16 min_path_points
uint16 max_time
uint16 max_simplification_time
---
# Result
trajectory_msgs/JointTrajectory path_to_pick
---