/candriver:
  ros__parameters:
    loop_frequency: 1000.
    
/base_controller:
  ros__parameters:

    loop_frequency: 1000.
    communication_rate: 10.

    precision: 0.0006
    error_margin: 0.05

    FFv_gain_0: 0.0
    FFa_gain_0: 0.
    Kd_gain_0: 80.0
    Ki_gain_0: 14000.0
    Kp_gain_0: 8000.0
    i_clamp_h_0: 120.
    i_clamp_l_0: -120.

    FFv_gain_1: 0.0
    FFa_gain_1: 0.
    Kd_gain_1: 80.0
    Ki_gain_1: 14000.0
    Kp_gain_1: 8000.0
    i_clamp_h_1: 100.
    i_clamp_l_1: -100.

    FFv_gain_2: 0.0
    FFa_gain_2: 0.
    Kd_gain_2: 80.0
    Ki_gain_2: 14000.0
    Kp_gain_2: 8000.0
    i_clamp_h_2: 80.
    i_clamp_l_2: -80.

    FFv_gain_3: 0.0
    FFa_gain_3: 0.
    Kd_gain_3: 60.0
    Ki_gain_3: 24000.0
    Kp_gain_3: 4000.0
    i_clamp_h_3: 40.
    i_clamp_l_3: -40.

    FFv_gain_4: 0.0
    FFa_gain_4: 0.
    Kd_gain_4: 60.0
    Ki_gain_4: 24000.0
    Kp_gain_4: 4000.0
    i_clamp_h_4: 40.
    i_clamp_l_4: -40.

    FFv_gain_5: 0.0
    FFa_gain_5: 0.
    Kd_gain_5: 60.0
    Ki_gain_5: 24000.0
    Kp_gain_5: 4000.0
    i_clamp_h_5: 40.
    i_clamp_l_5: -40.

    use_sim_time: false