/candriver:
  ros__parameters:
    loop_frequency: 500.
    
/base_controller:
  ros__parameters:

    loop_frequency: 500.
    communication_rate: 100.

    #friction

    FFv_gain_0: 0.
    FFa_gain_0: 0.
    Kd_gain_0: 0.1
    Ki_gain_0: 5.
    Kp_gain_0: 10.0
    Coulomb_friction_0: 0.
    i_clamp_h_0: 40.
    i_clamp_l_0: -40.

    FFv_gain_1: 0.
    FFa_gain_1: 0.
    Kd_gain_1: 0.1
    Ki_gain_1: 5.
    Kp_gain_1: 10.0
    Coulomb_friction_1: 0.
    i_clamp_h_1: 40.
    i_clamp_l_1: -40.


    FFv_gain_2: 0.
    FFa_gain_2: 0.
    Kd_gain_2: 0.1
    Ki_gain_2: 5.
    Kp_gain_2: 10.0
    Coulomb_friction_2: 0.
    i_clamp_h_2: 40.
    i_clamp_l_2: -40.

    FFv_gain_3: 0.
    FFa_gain_3: 0.
    Kd_gain_3: 0.1
    Ki_gain_3: 5.
    Kp_gain_3: 10.0
    Coulomb_friction_3: 0.
    i_clamp_h_3: 40.
    i_clamp_l_3: -40.

    FFv_gain_4: 0.
    FFa_gain_4: 0.
    Kd_gain_4: 0.1
    Ki_gain_4: 5.
    Kp_gain_4: 10.0
    Coulomb_friction_4: 0.
    i_clamp_h_4: 40.
    i_clamp_l_4: -40.

    FFv_gain_5: 0.
    FFa_gain_5: 0.
    Kd_gain_5: 0.1
    Ki_gain_5: 5.
    Kp_gain_5: 10.0
    Coulomb_friction_5: 0.
    i_clamp_h_5: 40.
    i_clamp_l_5: -40.



    use_sim_time: false
