/candriver:
  ros__parameters:
    loop_frequency: 1000.
    
/base_controller:
  ros__parameters:

    loop_frequency: 1000.
    communication_rate: 10.

    error_margin: 0.05

    FFv_gain_0: 0.0
    FFa_gain_0: 0.
    Kd_gain_0: 40.0
    Ki_gain_0: 500.0
    Kp_gain_0: 760.0
    i_clamp_h_0: 20.
    i_clamp_l_0: -20.

    FFv_gain_1: 0.0
    FFa_gain_1: 0.
    Kd_gain_1: 40.0
    Ki_gain_1: 1500.0
    Kp_gain_1: 540.0
    i_clamp_h_1: 25.
    i_clamp_l_1: -25.

    FFv_gain_2: 0.0
    FFa_gain_2: 0.
    Kd_gain_2: 30.0
    Ki_gain_2: 800.0
    Kp_gain_2: 320.0
    i_clamp_h_2: 25.
    i_clamp_l_2: -25.

    FFv_gain_3: 0.0
    FFa_gain_3: 0.
    Kd_gain_3: 30.0
    Ki_gain_3: 600.0
    Kp_gain_3: 350.0
    i_clamp_h_3: 15.
    i_clamp_l_3: -15.

    FFv_gain_4: 0.0
    FFa_gain_4: 0.
    Kd_gain_4: 30.0
    Ki_gain_4: 600.0
    Kp_gain_4: 350.0
    i_clamp_h_4: 15.
    i_clamp_l_4: -15.

    FFv_gain_5: 0.0
    FFa_gain_5: 0.
    Kd_gain_5: 30.0
    Ki_gain_5: 600.0
    Kp_gain_5: 350.0
    i_clamp_h_5: 15.
    i_clamp_l_5: -15.

    use_sim_time: false