/candriver:
  ros__parameters:
    loop_frequency: 500.
    
/base_controller:
  ros__parameters:

    loop_frequency: 500.
    communication_rate: 10.
    const_torque: 12.

    use_sim_time: false

