/candriver:
  ros__parameters:
    loop_frequency: 500.
    
/base_controller:
  ros__parameters:

    # sin_amp: 1.57
    # trajectory_period: 12.

    loop_frequency: 500.
    communication_rate: 10.

    error_margin: 0.09

    FFv_gain_0: 0.0
    FFa_gain_0: 0.
    Kd_gain_0: 100.0
    Ki_gain_0: 420.0
    Kp_gain_0: 760.0
    i_clamp_h_0: 20.
    i_clamp_l_0: -20.

    FFv_gain_1: 0.0
    FFa_gain_1: 0.
    Kd_gain_1: 100.0
    Ki_gain_1: 460.0
    Kp_gain_1: 720.0
    i_clamp_h_1: 25.
    i_clamp_l_1: -25.

    FFv_gain_2: 0.0
    FFa_gain_2: 0.
    Kd_gain_2: 60.0
    Ki_gain_2: 300.0
    Kp_gain_2: 480.0
    i_clamp_h_2: 25.
    i_clamp_l_2: -25.

    FFv_gain_3: 0.0
    FFa_gain_3: 0.
    Kd_gain_3: 15.0
    Ki_gain_3: 160.0
    Kp_gain_3: 380.0
    i_clamp_h_3: 15.
    i_clamp_l_3: -15.

    FFv_gain_4: 0.0
    FFa_gain_4: 0.
    Kd_gain_4: 10.0
    Ki_gain_4: 160.0
    Kp_gain_4: 380.0
    i_clamp_h_4: 15.
    i_clamp_l_4: -15.

    FFv_gain_5: 0.0
    FFa_gain_5: 0.
    Kd_gain_5: 10.0
    Ki_gain_5: 160.0
    Kp_gain_5: 380.0
    i_clamp_h_5: 15.
    i_clamp_l_5: -15.

    use_sim_time: false